Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
strip.crop((0, 200))

# This should result in an error:
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [111][0m, in [0;36m<module>[0;34m[0m
[0;32m----> 1[0m [43mstrip[49m[38;5;241;43m.[39;49m[43mcrop[49m[43m([49m[43m([49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[38;5;241;43m200[39;49m[43m)[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/striplog/striplog.py:2371[0m, in [0;36mStriplog.crop[0;34m(self, extent, copy)[0m
[1;32m   2368[0m first_ix [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mread_at(extent[[38;5;241m0[39m], index[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m   2369[0m last_ix [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mread_at(extent[[38;5;241m1[39m], index[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m-> 2371[0m first [38;5;241m=[39m [38;5;28;43mself[39;49m[43m[[49m[43mfirst_ix[49m[43m][49m[38;5;241m.[39msplit_at(extent[[38;5;241m0[39m])[[38;5;241m1[39m]
[1;32m   2372[0m last [38;5;241m=[39m [38;5;28mself[39m[last_ix][38;5;241m.[39msplit_at(extent[[38;5;241m1[39m])[[38;5;241m0[39m]
[1;32m   2374[0m new_list [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m__list[first_ix:last_ix[38;5;241m+[39m[38;5;241m1[39m][38;5;241m.[39mcopy()

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/striplog/striplog.py:137[0m, in [0;36mStriplog.__getitem__[0;34m(self, key)[0m
[1;32m    135[0m         [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    136[0m [38;5;28;01melse[39;00m:
[0;32m--> 137[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__list[49m[43m[[49m[43mkey[49m[43m][49m

[0;31mTypeError[0m: list indices must be integers or slices, not NoneType
TypeError: list indices must be integers or slices, not NoneType

